# Generated by Django 5.0.7 on 2024-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot1', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='preview_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
